/*
 * This file is generated by jOOQ.
*/
package br.com.tcc.dao.metadata.tables;


import br.com.tcc.dao.metadata.App;
import br.com.tcc.dao.metadata.Keys;
import br.com.tcc.dao.metadata.tables.records.ReferenceModelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferenceModel extends TableImpl<ReferenceModelRecord> {

    private static final long serialVersionUID = 1007690670;

    /**
     * The reference instance of <code>app.reference_model</code>
     */
    public static final ReferenceModel REFERENCE_MODEL = new ReferenceModel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReferenceModelRecord> getRecordType() {
        return ReferenceModelRecord.class;
    }

    /**
     * The column <code>app.reference_model.id_reference_model</code>.
     */
    public final TableField<ReferenceModelRecord, Integer> ID_REFERENCE_MODEL = createField("id_reference_model", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>app.reference_model.name</code>.
     */
    public final TableField<ReferenceModelRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>app.reference_model.knowledge_areas</code>.
     */
    public final TableField<ReferenceModelRecord, Object> KNOWLEDGE_AREAS = createField("knowledge_areas", org.jooq.impl.DefaultDataType.getDefaultDataType("json"), this, "");

    /**
     * Create a <code>app.reference_model</code> table reference
     */
    public ReferenceModel() {
        this("reference_model", null);
    }

    /**
     * Create an aliased <code>app.reference_model</code> table reference
     */
    public ReferenceModel(String alias) {
        this(alias, REFERENCE_MODEL);
    }

    private ReferenceModel(String alias, Table<ReferenceModelRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReferenceModel(String alias, Table<ReferenceModelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ReferenceModelRecord, Integer> getIdentity() {
        return Keys.IDENTITY_REFERENCE_MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReferenceModelRecord> getPrimaryKey() {
        return Keys.KEY_REFERENCE_MODEL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReferenceModelRecord>> getKeys() {
        return Arrays.<UniqueKey<ReferenceModelRecord>>asList(Keys.KEY_REFERENCE_MODEL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferenceModel as(String alias) {
        return new ReferenceModel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReferenceModel rename(String name) {
        return new ReferenceModel(name, null);
    }
}
