/*
 * This file is generated by jOOQ.
*/
package br.com.tcc.dao.metadata;


import br.com.tcc.dao.metadata.tables.Assessment;
import br.com.tcc.dao.metadata.tables.Company;
import br.com.tcc.dao.metadata.tables.MeasurementFramework;
import br.com.tcc.dao.metadata.tables.ReferenceModel;
import br.com.tcc.dao.metadata.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App extends SchemaImpl {

    private static final long serialVersionUID = -598427539;

    /**
     * The reference instance of <code>app</code>
     */
    public static final App APP = new App();

    /**
     * The table <code>app.assessment</code>.
     */
    public final Assessment ASSESSMENT = br.com.tcc.dao.metadata.tables.Assessment.ASSESSMENT;

    /**
     * The table <code>app.company</code>.
     */
    public final Company COMPANY = br.com.tcc.dao.metadata.tables.Company.COMPANY;

    /**
     * The table <code>app.measurement_framework</code>.
     */
    public final MeasurementFramework MEASUREMENT_FRAMEWORK = br.com.tcc.dao.metadata.tables.MeasurementFramework.MEASUREMENT_FRAMEWORK;

    /**
     * The table <code>app.reference_model</code>.
     */
    public final ReferenceModel REFERENCE_MODEL = br.com.tcc.dao.metadata.tables.ReferenceModel.REFERENCE_MODEL;

    /**
     * The table <code>app.user</code>.
     */
    public final User USER = br.com.tcc.dao.metadata.tables.User.USER;

    /**
     * No further instances allowed
     */
    private App() {
        super("app", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Assessment.ASSESSMENT,
            Company.COMPANY,
            MeasurementFramework.MEASUREMENT_FRAMEWORK,
            ReferenceModel.REFERENCE_MODEL,
            User.USER);
    }
}
