/*
 * This file is generated by jOOQ.
*/
package br.com.tcc.dao.metadata;


import br.com.tcc.dao.metadata.tables.Assessment;
import br.com.tcc.dao.metadata.tables.Company;
import br.com.tcc.dao.metadata.tables.DataSource;
import br.com.tcc.dao.metadata.tables.MeasurementFramework;
import br.com.tcc.dao.metadata.tables.ReferenceModel;
import br.com.tcc.dao.metadata.tables.User;
import br.com.tcc.dao.metadata.tables.records.AssessmentRecord;
import br.com.tcc.dao.metadata.tables.records.CompanyRecord;
import br.com.tcc.dao.metadata.tables.records.DataSourceRecord;
import br.com.tcc.dao.metadata.tables.records.MeasurementFrameworkRecord;
import br.com.tcc.dao.metadata.tables.records.ReferenceModelRecord;
import br.com.tcc.dao.metadata.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>app</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AssessmentRecord, Integer> IDENTITY_ASSESSMENT = Identities0.IDENTITY_ASSESSMENT;
    public static final Identity<CompanyRecord, Integer> IDENTITY_COMPANY = Identities0.IDENTITY_COMPANY;
    public static final Identity<DataSourceRecord, Integer> IDENTITY_DATA_SOURCE = Identities0.IDENTITY_DATA_SOURCE;
    public static final Identity<MeasurementFrameworkRecord, Integer> IDENTITY_MEASUREMENT_FRAMEWORK = Identities0.IDENTITY_MEASUREMENT_FRAMEWORK;
    public static final Identity<ReferenceModelRecord, Integer> IDENTITY_REFERENCE_MODEL = Identities0.IDENTITY_REFERENCE_MODEL;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AssessmentRecord> KEY_ASSESSMENT_PRIMARY = UniqueKeys0.KEY_ASSESSMENT_PRIMARY;
    public static final UniqueKey<CompanyRecord> KEY_COMPANY_PRIMARY = UniqueKeys0.KEY_COMPANY_PRIMARY;
    public static final UniqueKey<DataSourceRecord> KEY_DATA_SOURCE_PRIMARY = UniqueKeys0.KEY_DATA_SOURCE_PRIMARY;
    public static final UniqueKey<MeasurementFrameworkRecord> KEY_MEASUREMENT_FRAMEWORK_PRIMARY = UniqueKeys0.KEY_MEASUREMENT_FRAMEWORK_PRIMARY;
    public static final UniqueKey<MeasurementFrameworkRecord> KEY_MEASUREMENT_FRAMEWORK_NAME = UniqueKeys0.KEY_MEASUREMENT_FRAMEWORK_NAME;
    public static final UniqueKey<ReferenceModelRecord> KEY_REFERENCE_MODEL_PRIMARY = UniqueKeys0.KEY_REFERENCE_MODEL_PRIMARY;
    public static final UniqueKey<ReferenceModelRecord> KEY_REFERENCE_MODEL_NAME = UniqueKeys0.KEY_REFERENCE_MODEL_NAME;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_USER_USERNAME_UINDEX = UniqueKeys0.KEY_USER_USER_USERNAME_UINDEX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AssessmentRecord, UserRecord> ID_USER_ASSESSMENT_FK = ForeignKeys0.ID_USER_ASSESSMENT_FK;
    public static final ForeignKey<MeasurementFrameworkRecord, ReferenceModelRecord> ID_REFERENCE_MODEL_MEASUREMENT_FRAMEWORK_FK = ForeignKeys0.ID_REFERENCE_MODEL_MEASUREMENT_FRAMEWORK_FK;
    public static final ForeignKey<UserRecord, CompanyRecord> USER_ID_COMPANY_FK = ForeignKeys0.USER_ID_COMPANY_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AssessmentRecord, Integer> IDENTITY_ASSESSMENT = createIdentity(Assessment.ASSESSMENT, Assessment.ASSESSMENT.ID_ASSESSMENT);
        public static Identity<CompanyRecord, Integer> IDENTITY_COMPANY = createIdentity(Company.COMPANY, Company.COMPANY.ID_COMPANY);
        public static Identity<DataSourceRecord, Integer> IDENTITY_DATA_SOURCE = createIdentity(DataSource.DATA_SOURCE, DataSource.DATA_SOURCE.ID_DATA_SOURCE);
        public static Identity<MeasurementFrameworkRecord, Integer> IDENTITY_MEASUREMENT_FRAMEWORK = createIdentity(MeasurementFramework.MEASUREMENT_FRAMEWORK, MeasurementFramework.MEASUREMENT_FRAMEWORK.ID_MEASUREMENT_FRAMEWORK);
        public static Identity<ReferenceModelRecord, Integer> IDENTITY_REFERENCE_MODEL = createIdentity(ReferenceModel.REFERENCE_MODEL, ReferenceModel.REFERENCE_MODEL.ID_REFERENCE_MODEL);
        public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID_USER);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AssessmentRecord> KEY_ASSESSMENT_PRIMARY = createUniqueKey(Assessment.ASSESSMENT, "KEY_assessment_PRIMARY", Assessment.ASSESSMENT.ID_ASSESSMENT);
        public static final UniqueKey<CompanyRecord> KEY_COMPANY_PRIMARY = createUniqueKey(Company.COMPANY, "KEY_company_PRIMARY", Company.COMPANY.ID_COMPANY);
        public static final UniqueKey<DataSourceRecord> KEY_DATA_SOURCE_PRIMARY = createUniqueKey(DataSource.DATA_SOURCE, "KEY_data_source_PRIMARY", DataSource.DATA_SOURCE.ID_DATA_SOURCE);
        public static final UniqueKey<MeasurementFrameworkRecord> KEY_MEASUREMENT_FRAMEWORK_PRIMARY = createUniqueKey(MeasurementFramework.MEASUREMENT_FRAMEWORK, "KEY_measurement_framework_PRIMARY", MeasurementFramework.MEASUREMENT_FRAMEWORK.ID_MEASUREMENT_FRAMEWORK);
        public static final UniqueKey<MeasurementFrameworkRecord> KEY_MEASUREMENT_FRAMEWORK_NAME = createUniqueKey(MeasurementFramework.MEASUREMENT_FRAMEWORK, "KEY_measurement_framework_name", MeasurementFramework.MEASUREMENT_FRAMEWORK.NAME);
        public static final UniqueKey<ReferenceModelRecord> KEY_REFERENCE_MODEL_PRIMARY = createUniqueKey(ReferenceModel.REFERENCE_MODEL, "KEY_reference_model_PRIMARY", ReferenceModel.REFERENCE_MODEL.ID_REFERENCE_MODEL);
        public static final UniqueKey<ReferenceModelRecord> KEY_REFERENCE_MODEL_NAME = createUniqueKey(ReferenceModel.REFERENCE_MODEL, "KEY_reference_model_name", ReferenceModel.REFERENCE_MODEL.NAME);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID_USER);
        public static final UniqueKey<UserRecord> KEY_USER_USER_USERNAME_UINDEX = createUniqueKey(User.USER, "KEY_user_user_username_uindex", User.USER.USERNAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AssessmentRecord, UserRecord> ID_USER_ASSESSMENT_FK = createForeignKey(br.com.tcc.dao.metadata.Keys.KEY_USER_PRIMARY, Assessment.ASSESSMENT, "id_user_assessment_fk", Assessment.ASSESSMENT.ID_USER);
        public static final ForeignKey<MeasurementFrameworkRecord, ReferenceModelRecord> ID_REFERENCE_MODEL_MEASUREMENT_FRAMEWORK_FK = createForeignKey(br.com.tcc.dao.metadata.Keys.KEY_REFERENCE_MODEL_PRIMARY, MeasurementFramework.MEASUREMENT_FRAMEWORK, "id_reference_model_measurement_framework_fk", MeasurementFramework.MEASUREMENT_FRAMEWORK.ID_REFERENCE_MODEL);
        public static final ForeignKey<UserRecord, CompanyRecord> USER_ID_COMPANY_FK = createForeignKey(br.com.tcc.dao.metadata.Keys.KEY_COMPANY_PRIMARY, User.USER, "user_id_company_fk", User.USER.ID_COMPANY);
    }
}
