/*
 * This file is generated by jOOQ.
*/
package br.com.spring.jersey.dao.metadata;


import br.com.spring.jersey.dao.metadata.tables.Company;
import br.com.spring.jersey.dao.metadata.tables.KnowledgeArea;
import br.com.spring.jersey.dao.metadata.tables.Process;
import br.com.spring.jersey.dao.metadata.tables.ReKnowledgeAreaReferenceModel;
import br.com.spring.jersey.dao.metadata.tables.ReProcessKnowledgeArea;
import br.com.spring.jersey.dao.metadata.tables.ReferenceModel;
import br.com.spring.jersey.dao.metadata.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App extends SchemaImpl {

    private static final long serialVersionUID = -318151062;

    /**
     * The reference instance of <code>app</code>
     */
    public static final App APP = new App();

    /**
     * The table <code>app.company</code>.
     */
    public final Company COMPANY = br.com.spring.jersey.dao.metadata.tables.Company.COMPANY;

    /**
     * The table <code>app.knowledge_area</code>.
     */
    public final KnowledgeArea KNOWLEDGE_AREA = br.com.spring.jersey.dao.metadata.tables.KnowledgeArea.KNOWLEDGE_AREA;

    /**
     * The table <code>app.process</code>.
     */
    public final Process PROCESS = br.com.spring.jersey.dao.metadata.tables.Process.PROCESS;

    /**
     * The table <code>app.reference_model</code>.
     */
    public final ReferenceModel REFERENCE_MODEL = br.com.spring.jersey.dao.metadata.tables.ReferenceModel.REFERENCE_MODEL;

    /**
     * The table <code>app.re_knowledge_area_reference_model</code>.
     */
    public final ReKnowledgeAreaReferenceModel RE_KNOWLEDGE_AREA_REFERENCE_MODEL = br.com.spring.jersey.dao.metadata.tables.ReKnowledgeAreaReferenceModel.RE_KNOWLEDGE_AREA_REFERENCE_MODEL;

    /**
     * The table <code>app.re_process_knowledge_area</code>.
     */
    public final ReProcessKnowledgeArea RE_PROCESS_KNOWLEDGE_AREA = br.com.spring.jersey.dao.metadata.tables.ReProcessKnowledgeArea.RE_PROCESS_KNOWLEDGE_AREA;

    /**
     * The table <code>app.user</code>.
     */
    public final User USER = br.com.spring.jersey.dao.metadata.tables.User.USER;

    /**
     * No further instances allowed
     */
    private App() {
        super("app", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Company.COMPANY,
            KnowledgeArea.KNOWLEDGE_AREA,
            Process.PROCESS,
            ReferenceModel.REFERENCE_MODEL,
            ReKnowledgeAreaReferenceModel.RE_KNOWLEDGE_AREA_REFERENCE_MODEL,
            ReProcessKnowledgeArea.RE_PROCESS_KNOWLEDGE_AREA,
            User.USER);
    }
}
