/*
 * This file is generated by jOOQ.
*/
package br.com.spring.jersey.dao.metadata.tables;


import br.com.spring.jersey.dao.metadata.App;
import br.com.spring.jersey.dao.metadata.Keys;
import br.com.spring.jersey.dao.metadata.tables.records.ReKnowledgeAreaReferenceModelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReKnowledgeAreaReferenceModel extends TableImpl<ReKnowledgeAreaReferenceModelRecord> {

    private static final long serialVersionUID = 577950461;

    /**
     * The reference instance of <code>app.re_knowledge_area_reference_model</code>
     */
    public static final ReKnowledgeAreaReferenceModel RE_KNOWLEDGE_AREA_REFERENCE_MODEL = new ReKnowledgeAreaReferenceModel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReKnowledgeAreaReferenceModelRecord> getRecordType() {
        return ReKnowledgeAreaReferenceModelRecord.class;
    }

    /**
     * The column <code>app.re_knowledge_area_reference_model.id_knowledge_area</code>.
     */
    public final TableField<ReKnowledgeAreaReferenceModelRecord, Integer> ID_KNOWLEDGE_AREA = createField("id_knowledge_area", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>app.re_knowledge_area_reference_model.id_reference_model</code>.
     */
    public final TableField<ReKnowledgeAreaReferenceModelRecord, Integer> ID_REFERENCE_MODEL = createField("id_reference_model", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>app.re_knowledge_area_reference_model</code> table reference
     */
    public ReKnowledgeAreaReferenceModel() {
        this("re_knowledge_area_reference_model", null);
    }

    /**
     * Create an aliased <code>app.re_knowledge_area_reference_model</code> table reference
     */
    public ReKnowledgeAreaReferenceModel(String alias) {
        this(alias, RE_KNOWLEDGE_AREA_REFERENCE_MODEL);
    }

    private ReKnowledgeAreaReferenceModel(String alias, Table<ReKnowledgeAreaReferenceModelRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReKnowledgeAreaReferenceModel(String alias, Table<ReKnowledgeAreaReferenceModelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReKnowledgeAreaReferenceModelRecord> getPrimaryKey() {
        return Keys.KEY_RE_KNOWLEDGE_AREA_REFERENCE_MODEL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReKnowledgeAreaReferenceModelRecord>> getKeys() {
        return Arrays.<UniqueKey<ReKnowledgeAreaReferenceModelRecord>>asList(Keys.KEY_RE_KNOWLEDGE_AREA_REFERENCE_MODEL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ReKnowledgeAreaReferenceModelRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReKnowledgeAreaReferenceModelRecord, ?>>asList(Keys.RE_KNOWLEDGE_AREA_REFERENCE_MODEL_ID_KNOWLEDGE_AREA_FK, Keys.RE_KNOWLEDGE_AREA_REFERENCE_MODEL_ID_REFERENCE_MODEL_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReKnowledgeAreaReferenceModel as(String alias) {
        return new ReKnowledgeAreaReferenceModel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReKnowledgeAreaReferenceModel rename(String name) {
        return new ReKnowledgeAreaReferenceModel(name, null);
    }
}
