/*
 * This file is generated by jOOQ.
*/
package br.com.spring.jersey.dao.metadata.tables;


import br.com.spring.jersey.dao.metadata.App;
import br.com.spring.jersey.dao.metadata.Keys;
import br.com.spring.jersey.dao.metadata.tables.records.ReProcessKnowledgeAreaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReProcessKnowledgeArea extends TableImpl<ReProcessKnowledgeAreaRecord> {

    private static final long serialVersionUID = 959400049;

    /**
     * The reference instance of <code>app.re_process_knowledge_area</code>
     */
    public static final ReProcessKnowledgeArea RE_PROCESS_KNOWLEDGE_AREA = new ReProcessKnowledgeArea();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReProcessKnowledgeAreaRecord> getRecordType() {
        return ReProcessKnowledgeAreaRecord.class;
    }

    /**
     * The column <code>app.re_process_knowledge_area.id_process</code>.
     */
    public final TableField<ReProcessKnowledgeAreaRecord, Integer> ID_PROCESS = createField("id_process", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>app.re_process_knowledge_area.id_knowledge_area</code>.
     */
    public final TableField<ReProcessKnowledgeAreaRecord, Integer> ID_KNOWLEDGE_AREA = createField("id_knowledge_area", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>app.re_process_knowledge_area</code> table reference
     */
    public ReProcessKnowledgeArea() {
        this("re_process_knowledge_area", null);
    }

    /**
     * Create an aliased <code>app.re_process_knowledge_area</code> table reference
     */
    public ReProcessKnowledgeArea(String alias) {
        this(alias, RE_PROCESS_KNOWLEDGE_AREA);
    }

    private ReProcessKnowledgeArea(String alias, Table<ReProcessKnowledgeAreaRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReProcessKnowledgeArea(String alias, Table<ReProcessKnowledgeAreaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReProcessKnowledgeAreaRecord> getPrimaryKey() {
        return Keys.KEY_RE_PROCESS_KNOWLEDGE_AREA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReProcessKnowledgeAreaRecord>> getKeys() {
        return Arrays.<UniqueKey<ReProcessKnowledgeAreaRecord>>asList(Keys.KEY_RE_PROCESS_KNOWLEDGE_AREA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ReProcessKnowledgeAreaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReProcessKnowledgeAreaRecord, ?>>asList(Keys.RE_PROCESS_KNOWLEDGE_AREA_ID_PROCESS_FK, Keys.RE_PROCESS_KNOWLEDGE_AREA_ID_KNOWLEDGE_AREA_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReProcessKnowledgeArea as(String alias) {
        return new ReProcessKnowledgeArea(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReProcessKnowledgeArea rename(String name) {
        return new ReProcessKnowledgeArea(name, null);
    }
}
