/*
 * This file is generated by jOOQ.
*/
package br.com.tcc.dao.metadata.tables.records;


import br.com.tcc.dao.metadata.tables.DataSource;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataSourceRecord extends UpdatableRecordImpl<DataSourceRecord> implements Record7<Integer, Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -54015742;

    /**
     * Setter for <code>app.data_source.id_data_source</code>.
     */
    public void setIdDataSource(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.data_source.id_data_source</code>.
     */
    public Integer getIdDataSource() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>app.data_source.id_company</code>.
     */
    public void setIdCompany(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.data_source.id_company</code>.
     */
    public Integer getIdCompany() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>app.data_source.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>app.data_source.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>app.data_source.url</code>.
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>app.data_source.url</code>.
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>app.data_source.authenticated</code>.
     */
    public void setAuthenticated(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>app.data_source.authenticated</code>.
     */
    public String getAuthenticated() {
        return (String) get(4);
    }

    /**
     * Setter for <code>app.data_source.user</code>.
     */
    public void setUser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>app.data_source.user</code>.
     */
    public String getUser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>app.data_source.password</code>.
     */
    public void setPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>app.data_source.password</code>.
     */
    public String getPassword() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DataSource.DATA_SOURCE.ID_DATA_SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DataSource.DATA_SOURCE.ID_COMPANY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DataSource.DATA_SOURCE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DataSource.DATA_SOURCE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DataSource.DATA_SOURCE.AUTHENTICATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DataSource.DATA_SOURCE.USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DataSource.DATA_SOURCE.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdDataSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdCompany();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAuthenticated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSourceRecord value1(Integer value) {
        setIdDataSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSourceRecord value2(Integer value) {
        setIdCompany(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSourceRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSourceRecord value4(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSourceRecord value5(String value) {
        setAuthenticated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSourceRecord value6(String value) {
        setUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSourceRecord value7(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSourceRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataSourceRecord
     */
    public DataSourceRecord() {
        super(DataSource.DATA_SOURCE);
    }

    /**
     * Create a detached, initialised DataSourceRecord
     */
    public DataSourceRecord(Integer idDataSource, Integer idCompany, String name, String url, String authenticated, String user, String password) {
        super(DataSource.DATA_SOURCE);

        set(0, idDataSource);
        set(1, idCompany);
        set(2, name);
        set(3, url);
        set(4, authenticated);
        set(5, user);
        set(6, password);
    }
}
