/*
 * This file is generated by jOOQ.
*/
package br.com.tcc.dao.metadata.tables.records;


import br.com.tcc.dao.metadata.enums.EvaluationStatus;
import br.com.tcc.dao.metadata.tables.Evaluation;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EvaluationRecord extends UpdatableRecordImpl<EvaluationRecord> implements Record6<Integer, LocalDateTime, Integer, EvaluationStatus, Integer, Object> {

    private static final long serialVersionUID = 1344326396;

    /**
     * Setter for <code>app.evaluation.id_evaluation</code>.
     */
    public void setIdEvaluation(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.evaluation.id_evaluation</code>.
     */
    public Integer getIdEvaluation() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>app.evaluation.date</code>.
     */
    public void setDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.evaluation.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>app.evaluation.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>app.evaluation.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>app.evaluation.status</code>.
     */
    public void setStatus(EvaluationStatus value) {
        set(3, value);
    }

    /**
     * Getter for <code>app.evaluation.status</code>.
     */
    public EvaluationStatus getStatus() {
        return (EvaluationStatus) get(3);
    }

    /**
     * Setter for <code>app.evaluation.id_measurement_framework</code>.
     */
    public void setIdMeasurementFramework(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>app.evaluation.id_measurement_framework</code>.
     */
    public Integer getIdMeasurementFramework() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>app.evaluation.json_evaluation</code>.
     */
    public void setJsonEvaluation(Object value) {
        set(5, value);
    }

    /**
     * Getter for <code>app.evaluation.json_evaluation</code>.
     */
    public Object getJsonEvaluation() {
        return (Object) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, LocalDateTime, Integer, EvaluationStatus, Integer, Object> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, LocalDateTime, Integer, EvaluationStatus, Integer, Object> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Evaluation.EVALUATION.ID_EVALUATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return Evaluation.EVALUATION.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Evaluation.EVALUATION.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<EvaluationStatus> field4() {
        return Evaluation.EVALUATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Evaluation.EVALUATION.ID_MEASUREMENT_FRAMEWORK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field6() {
        return Evaluation.EVALUATION.JSON_EVALUATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdEvaluation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluationStatus value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdMeasurementFramework();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value6() {
        return getJsonEvaluation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluationRecord value1(Integer value) {
        setIdEvaluation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluationRecord value2(LocalDateTime value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluationRecord value3(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluationRecord value4(EvaluationStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluationRecord value5(Integer value) {
        setIdMeasurementFramework(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluationRecord value6(Object value) {
        setJsonEvaluation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluationRecord values(Integer value1, LocalDateTime value2, Integer value3, EvaluationStatus value4, Integer value5, Object value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EvaluationRecord
     */
    public EvaluationRecord() {
        super(Evaluation.EVALUATION);
    }

    /**
     * Create a detached, initialised EvaluationRecord
     */
    public EvaluationRecord(Integer idEvaluation, LocalDateTime date, Integer idUser, EvaluationStatus status, Integer idMeasurementFramework, Object jsonEvaluation) {
        super(Evaluation.EVALUATION);

        set(0, idEvaluation);
        set(1, date);
        set(2, idUser);
        set(3, status);
        set(4, idMeasurementFramework);
        set(5, jsonEvaluation);
    }
}
