/*
 * This file is generated by jOOQ.
*/
package br.com.tcc.dao.metadata.tables.records;


import br.com.tcc.dao.metadata.tables.MeasurementFramework;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeasurementFrameworkRecord extends UpdatableRecordImpl<MeasurementFrameworkRecord> implements Record4<Integer, String, Integer, Object> {

    private static final long serialVersionUID = 1507333823;

    /**
     * Setter for <code>app.measurement_framework.id_measurement_framework</code>.
     */
    public void setIdMeasurementFramework(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.measurement_framework.id_measurement_framework</code>.
     */
    public Integer getIdMeasurementFramework() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>app.measurement_framework.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.measurement_framework.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>app.measurement_framework.id_reference_model</code>.
     */
    public void setIdReferenceModel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>app.measurement_framework.id_reference_model</code>.
     */
    public Integer getIdReferenceModel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>app.measurement_framework.json_measurement_framework</code>.
     */
    public void setJsonMeasurementFramework(Object value) {
        set(3, value);
    }

    /**
     * Getter for <code>app.measurement_framework.json_measurement_framework</code>.
     */
    public Object getJsonMeasurementFramework() {
        return (Object) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MeasurementFramework.MEASUREMENT_FRAMEWORK.ID_MEASUREMENT_FRAMEWORK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MeasurementFramework.MEASUREMENT_FRAMEWORK.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MeasurementFramework.MEASUREMENT_FRAMEWORK.ID_REFERENCE_MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field4() {
        return MeasurementFramework.MEASUREMENT_FRAMEWORK.JSON_MEASUREMENT_FRAMEWORK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdMeasurementFramework();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdReferenceModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value4() {
        return getJsonMeasurementFramework();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementFrameworkRecord value1(Integer value) {
        setIdMeasurementFramework(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementFrameworkRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementFrameworkRecord value3(Integer value) {
        setIdReferenceModel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementFrameworkRecord value4(Object value) {
        setJsonMeasurementFramework(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementFrameworkRecord values(Integer value1, String value2, Integer value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MeasurementFrameworkRecord
     */
    public MeasurementFrameworkRecord() {
        super(MeasurementFramework.MEASUREMENT_FRAMEWORK);
    }

    /**
     * Create a detached, initialised MeasurementFrameworkRecord
     */
    public MeasurementFrameworkRecord(Integer idMeasurementFramework, String name, Integer idReferenceModel, Object jsonMeasurementFramework) {
        super(MeasurementFramework.MEASUREMENT_FRAMEWORK);

        set(0, idMeasurementFramework);
        set(1, name);
        set(2, idReferenceModel);
        set(3, jsonMeasurementFramework);
    }
}
