/*
 * This file is generated by jOOQ.
*/
package br.com.spring.jersey.dao.metadata.tables.records;


import br.com.spring.jersey.dao.metadata.tables.KnowledgeArea;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KnowledgeAreaRecord extends UpdatableRecordImpl<KnowledgeAreaRecord> implements Record4<Integer, String, String, Object> {

    private static final long serialVersionUID = 110129841;

    /**
     * Setter for <code>app.knowledge_area.id_knowledge_area</code>.
     */
    public void setIdKnowledgeArea(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.knowledge_area.id_knowledge_area</code>.
     */
    public Integer getIdKnowledgeArea() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>app.knowledge_area.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.knowledge_area.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>app.knowledge_area.purpose</code>.
     */
    public void setPurpose(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>app.knowledge_area.purpose</code>.
     */
    public String getPurpose() {
        return (String) get(2);
    }

    /**
     * Setter for <code>app.knowledge_area.json_knowledge_area</code>.
     */
    public void setJsonKnowledgeArea(Object value) {
        set(3, value);
    }

    /**
     * Getter for <code>app.knowledge_area.json_knowledge_area</code>.
     */
    public Object getJsonKnowledgeArea() {
        return (Object) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return KnowledgeArea.KNOWLEDGE_AREA.ID_KNOWLEDGE_AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return KnowledgeArea.KNOWLEDGE_AREA.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return KnowledgeArea.KNOWLEDGE_AREA.PURPOSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field4() {
        return KnowledgeArea.KNOWLEDGE_AREA.JSON_KNOWLEDGE_AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdKnowledgeArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPurpose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value4() {
        return getJsonKnowledgeArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KnowledgeAreaRecord value1(Integer value) {
        setIdKnowledgeArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KnowledgeAreaRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KnowledgeAreaRecord value3(String value) {
        setPurpose(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KnowledgeAreaRecord value4(Object value) {
        setJsonKnowledgeArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KnowledgeAreaRecord values(Integer value1, String value2, String value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KnowledgeAreaRecord
     */
    public KnowledgeAreaRecord() {
        super(KnowledgeArea.KNOWLEDGE_AREA);
    }

    /**
     * Create a detached, initialised KnowledgeAreaRecord
     */
    public KnowledgeAreaRecord(Integer idKnowledgeArea, String name, String purpose, Object jsonKnowledgeArea) {
        super(KnowledgeArea.KNOWLEDGE_AREA);

        set(0, idKnowledgeArea);
        set(1, name);
        set(2, purpose);
        set(3, jsonKnowledgeArea);
    }
}
