/*
 * This file is generated by jOOQ.
*/
package br.com.spring.jersey.dao.metadata.tables.records;


import br.com.spring.jersey.dao.metadata.tables.ReKnowledgeAreaReferenceModel;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReKnowledgeAreaReferenceModelRecord extends UpdatableRecordImpl<ReKnowledgeAreaReferenceModelRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1522425487;

    /**
     * Setter for <code>app.re_knowledge_area_reference_model.id_knowledge_area</code>.
     */
    public void setIdKnowledgeArea(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.re_knowledge_area_reference_model.id_knowledge_area</code>.
     */
    public Integer getIdKnowledgeArea() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>app.re_knowledge_area_reference_model.id_reference_model</code>.
     */
    public void setIdReferenceModel(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.re_knowledge_area_reference_model.id_reference_model</code>.
     */
    public Integer getIdReferenceModel() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ReKnowledgeAreaReferenceModel.RE_KNOWLEDGE_AREA_REFERENCE_MODEL.ID_KNOWLEDGE_AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ReKnowledgeAreaReferenceModel.RE_KNOWLEDGE_AREA_REFERENCE_MODEL.ID_REFERENCE_MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdKnowledgeArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdReferenceModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReKnowledgeAreaReferenceModelRecord value1(Integer value) {
        setIdKnowledgeArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReKnowledgeAreaReferenceModelRecord value2(Integer value) {
        setIdReferenceModel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReKnowledgeAreaReferenceModelRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReKnowledgeAreaReferenceModelRecord
     */
    public ReKnowledgeAreaReferenceModelRecord() {
        super(ReKnowledgeAreaReferenceModel.RE_KNOWLEDGE_AREA_REFERENCE_MODEL);
    }

    /**
     * Create a detached, initialised ReKnowledgeAreaReferenceModelRecord
     */
    public ReKnowledgeAreaReferenceModelRecord(Integer idKnowledgeArea, Integer idReferenceModel) {
        super(ReKnowledgeAreaReferenceModel.RE_KNOWLEDGE_AREA_REFERENCE_MODEL);

        set(0, idKnowledgeArea);
        set(1, idReferenceModel);
    }
}
